#
# Copyright (c) 2016 The Ontario Institute for Cancer Research. All rights reserved.
#
# This program and the accompanying materials are made available under the terms of the GNU Public License v3.0.
# You should have received a copy of the GNU General Public License along with
# this program. If not, see <http://www.gnu.org/licenses/>.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
# SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
# TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
# OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ICGC Download Client - Configuration
#

# Common
logfile: /Users/g2wilson/git/icgc-get/mnt/logfile.log # TODO: This should end in .log!
udt: false
transport.memory: 1

# IGCC Storage
icgc:
  access:
  path: /icgc/icgc-storage-client/bin/icgc-storage-client
  transport.file.from: remote
  transport.parallel: 6

# GDC
gdc:
  access:
  path: /icgc/gdc-data-transfer-tool/gdc-client
  transport.parallel: 6

# EGA
ega:
  username:
  password:
  access:
  path: /icgc/ega-download-demo/EgaDemoClient.jar
  transport.parallel: 1

# CGHub
cghub:
  access: https://cghub.ucsc.edu/software/downloads/cghub_public.key
  path: /icgc/genetorrent/bin/gtdownload
  transport.parallel: 8



